In [3]:
a = [[1,2,3],[4,5,6],[6,7,8]]

In [4]:
import numpy as np
x = np.array(a)

In [5]:
print(x)

[[1 2 3]
 [4 5 6]
 [6 7 8]]


In [7]:
print(x[0,0])

1


In [13]:
ax = np.ones(10,'str')
print(ax)

['1' '1' '1' '1' '1' '1' '1' '1' '1' '1']


In [14]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [21]:

ax = np.array([np.arange(10)**2,np.arange(10)**3])
print(ax)

[[  0   1   4   9  16  25  36  49  64  81]
 [  0   1   8  27  64 125 216 343 512 729]]


In [22]:
#zip() method....

In [24]:
np.where(ax%2==0,1,0)#even = 1 , odd = 0

array([[1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0]])

# pandas

- integrated data manipulation and analysis capabilities
- integration with data visualization libraries
- built-in time series capabilitites
- optimized for speed
- built-in support for grabbing data from multiple sources
 - csv, html, xls, google, world bank, fred etc.,.

# 
- pandas organizes data into two data objects
  - series: one dimensional array objects

In [38]:
import pandas as pd
x = pd.DataFrame([[1,2,3],[1,2,3]],columns=["a","b","c"])
print(x)

   a  b  c
0  1  2  3
1  1  2  3


In [39]:
#x.set_index("a",inplace=True)

In [40]:
print(x)

   a  b  c
0  1  2  3
1  1  2  3


In [41]:
x["b"] #getting column data

0    2
1    2
Name: b, dtype: int64

In [43]:
x.loc[0] #getting  row data

a    1
b    2
c    3
Name: 0, dtype: int64

In [46]:
x.iloc[1] #getting row by row number

a    1
b    2
c    3
Name: 1, dtype: int64

In [47]:
x[["c","b"]]

c  b
0  3  2
1  3  2

In [48]:
x.loc[0,"c"]

3

In [49]:
x.loc[1:]

a  b  c
1  1  2  3

In [50]:
import pandas as pd

In [52]:
!pip install openpyxl

In [3]:
import nltk