# Using inbuilt dataset

## Import Dataset

In [9]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
X, y = load_iris(return_X_y=True)

## Train Test Split

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [33]:
gnb = GaussianNB()
gnb.fit(X_train, y_train)

GaussianNB()

## Predict the new sample

In [34]:
y_pred = gnb.predict(X_test)

In [35]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print("Classification Report: \n ########################################################################### \n", classification_report(y_test,y_pred),"\n ########################################################################### \n")
print("Confusion Matrix: \n ########################################################################### \n",confusion_matrix(y_test,y_pred),"\n ########################################################################### \n")
print("Accuracy:",accuracy_score(y_test,y_pred))

Classification Report: 
 ########################################################################### 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       0.93      1.00      0.96        13
           2       1.00      0.83      0.91         6

    accuracy                           0.97        30
   macro avg       0.98      0.94      0.96        30
weighted avg       0.97      0.97      0.97        30
 
 ########################################################################### 

Confusion Matrix: 
 ########################################################################### 
 [[11  0  0]
 [ 0 13  0]
 [ 0  1  5]] 
 ########################################################################### 

Accuracy: 0.9666666666666667


## Feature Scaling

In [36]:
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import MinMaxScaler

In [37]:
clf = make_pipeline(MinMaxScaler(), GaussianNB())

In [38]:
clf.fit(X_train, y_train) 

Pipeline(steps=[('minmaxscaler', MinMaxScaler()), ('gaussiannb', GaussianNB())])

In [39]:
y_pred = clf.predict(X_test)

In [40]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print("Classification Report: \n ########################################################################### \n", classification_report(y_test,y_pred),"\n ########################################################################### \n")
print("Confusion Matrix: \n ########################################################################### \n",confusion_matrix(y_test,y_pred),"\n ########################################################################### \n")
print("Accuracy:",accuracy_score(y_test,y_pred))

Classification Report: 
 ########################################################################### 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       0.93      1.00      0.96        13
           2       1.00      0.83      0.91         6

    accuracy                           0.97        30
   macro avg       0.98      0.94      0.96        30
weighted avg       0.97      0.97      0.97        30
 
 ########################################################################### 

Confusion Matrix: 
 ########################################################################### 
 [[11  0  0]
 [ 0 13  0]
 [ 0  1  5]] 
 ########################################################################### 

Accuracy: 0.9666666666666667


# Using User_data.csv

## Importing the dataset

In [51]:
import numpy as np  
import matplotlib.pyplot as mtp  
import pandas as pd  
  
# Importing the dataset  
dataset = pd.read_csv('User_data.csv')  
x = dataset.iloc[:, [2, 3]].values  
y = dataset.iloc[:, 4].values  

## Splitting data and Training

In [52]:
# Splitting the dataset into the Training set and Test set  
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 0)  
  
# Feature Scaling  
from sklearn.preprocessing import StandardScaler  
sc = StandardScaler()  
x_train = sc.fit_transform(x_train)  
x_test = sc.transform(x_test)  

In [53]:
# # Feature Scaling  
# from sklearn.preprocessing import MinMaxScaler  
# sc = MinMaxScaler()  
# x_train = sc.fit_transform(x_train)  
# x_test = sc.transform(x_test)  

In [54]:
# Fitting Naive Bayes to the Training set  
from sklearn.naive_bayes import GaussianNB  
classifier = GaussianNB()  
classifier.fit(x_train, y_train)  

GaussianNB()

## Prediction and Evaluation

In [55]:
# Predicting the Test set results  
y_pred = classifier.predict(x_test)  

In [56]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print("Classification Report: \n ########################################################################### \n", classification_report(y_test,y_pred),"\n ########################################################################### \n")
print("Confusion Matrix: \n ########################################################################### \n",confusion_matrix(y_test,y_pred),"\n ########################################################################### \n")
print("Accuracy:",accuracy_score(y_test,y_pred))

Classification Report: 
 ########################################################################### 
               precision    recall  f1-score   support

           0       0.90      0.96      0.93        68
           1       0.89      0.78      0.83        32

    accuracy                           0.90       100
   macro avg       0.90      0.87      0.88       100
weighted avg       0.90      0.90      0.90       100
 
 ########################################################################### 

Confusion Matrix: 
 ########################################################################### 
 [[65  3]
 [ 7 25]] 
 ########################################################################### 

Accuracy: 0.9
